// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compMatCalcTest
NumericMatrix compMatCalcTest(NumericMatrix x, double sigC);
RcppExport SEXP _fooRoLE_compMatCalcTest(SEXP xSEXP, SEXP sigCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigC(sigCSEXP);
    rcpp_result_gen = Rcpp::wrap(compMatCalcTest(x, sigC));
    return rcpp_result_gen;
END_RCPP
}
// envDistCalcTest
NumericVector envDistCalcTest(NumericMatrix x, NumericMatrix envOptim, double sigE);
RcppExport SEXP _fooRoLE_envDistCalcTest(SEXP xSEXP, SEXP envOptimSEXP, SEXP sigESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type envOptim(envOptimSEXP);
    Rcpp::traits::input_parameter< double >::type sigE(sigESEXP);
    rcpp_result_gen = Rcpp::wrap(envDistCalcTest(x, envOptim, sigE));
    return rcpp_result_gen;
END_RCPP
}
// BigOlTester
List BigOlTester(S4 x);
RcppExport SEXP _fooRoLE_BigOlTester(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(BigOlTester(x));
    return rcpp_result_gen;
END_RCPP
}
// simOO
List simOO(S4 x);
RcppExport SEXP _fooRoLE_simOO(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(simOO(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fooRoLE_compMatCalcTest", (DL_FUNC) &_fooRoLE_compMatCalcTest, 2},
    {"_fooRoLE_envDistCalcTest", (DL_FUNC) &_fooRoLE_envDistCalcTest, 3},
    {"_fooRoLE_BigOlTester", (DL_FUNC) &_fooRoLE_BigOlTester, 1},
    {"_fooRoLE_simOO", (DL_FUNC) &_fooRoLE_simOO, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fooRoLE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
