# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compMatCalcTest <- function(x, sigC) {
    .Call(`_fooRoLE_compMatCalcTest`, x, sigC)
}

envDistCalcTest <- function(x, envOptim, sigE) {
    .Call(`_fooRoLE_envDistCalcTest`, x, envOptim, sigE)
}

BigOlTester <- function(x) {
    .Call(`_fooRoLE_BigOlTester`, x)
}

simOO <- function(x) {
    .Call(`_fooRoLE_simOO`, x)
}

